#spring:
#  servlet:
#    multipart:
#      enabled: true #开启文件上传
#      max-file-size: 10MB #限制文件上传大小为10M
#
#  datasource:
#    url: jdbc:mysql://8.210.233.50:3306/jwk_down?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
#    username: root
#    password: Awert159@
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      initial-size: 5 #连接池初始化大小
#      min-idle: 10 #最小空闲连接数
#      max-active: 20 #最大连接数
#      web-stat-filter:
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
#      stat-view-servlet: #访问监控网页的登录用户名和密码
#        login-username: druid
#        login-password: druid
#noAuth:
#  url: "/admin/**"
#
#token:
#  secretKey: jiwk
#  expireSec: 86400000 # 过期时间一天
#
#mybatis-plus:
#  mapper-locations: classpath*:com.jwk.down.web/dao/*.xml
#  config-location: classpath:mybatis-config.xml
#
